//
// Copyright © 2022 Hardcore Engineering Inc.
// Copyright © 2026 Intabia Fusion.
//
// Licensed under the Eclipse Public License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License. You may
// obtain a copy of the License at https://www.eclipse.org/legal/epl-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//
// See the License for the specific language governing permissions and
// limitations under the License.
//

import { type Ref } from '@hcengineering/core'
import type { IntlString } from '@hcengineering/platform'
import { mergeIds } from '@hcengineering/platform'
import setting, { settingId } from '@hcengineering/setting'
import { type AnyComponent } from '@hcengineering/ui/src/types'
import { type Widget } from '@hcengineering/workbench'

export default mergeIds(settingId, setting, {
  ids: {
    SettingsWidget: '' as Ref<Widget>
  },
  component: {
    EditEnum: '' as AnyComponent,
    ManageSpaceTypes: '' as AnyComponent,
    ManageSpaceTypesTools: '' as AnyComponent,
    ManageSpaceTypeContent: '' as AnyComponent,
    Spaces: '' as AnyComponent,
    AddSocialId: '' as AnyComponent
  },
  string: {
    IntegrationDisabled: '' as IntlString,
    IntegrationDisabledSetting: '' as IntlString,
    IntegrationDisabledDescr: '' as IntlString,
    IntegrationWith: '' as IntlString,
    DeleteStatus: '' as IntlString,
    DeleteStatusConfirm: '' as IntlString,
    DeleteAttribute: '' as IntlString,
    DeleteAttributeConfirm: '' as IntlString,
    DeleteAttributeExistConfirm: '' as IntlString,
    DeleteMixin: '' as IntlString,
    DeleteMixinConfirm: '' as IntlString,
    DeleteMixinExistConfirm: '' as IntlString,
    Attribute: '' as IntlString,
    Attributes: '' as IntlString,
    Custom: '' as IntlString,
    WithTime: '' as IntlString,
    DateMode: '' as IntlString,
    Type: '' as IntlString,
    CreatingAttribute: '' as IntlString,
    EditAttribute: '' as IntlString,
    CreateEnum: '' as IntlString,
    EditEnum: '' as IntlString,
    Enums: '' as IntlString,
    EnumsSettingHint: '' as IntlString,
    EnumTitle: '' as IntlString,
    EnumsCount: '' as IntlString,
    ProjectTypesCount: '' as IntlString,
    Options: '' as IntlString,
    EnterOptionTitle: '' as IntlString,
    NewEnumDialogClose: '' as IntlString,
    NewEnumDialogCloseNote: '' as IntlString,
    NewValue: '' as IntlString,
    Leave: '' as IntlString,
    LeaveDescr: '' as IntlString,
    Select: '' as IntlString,
    AddOwner: '' as IntlString,
    ReadonlyGuest: '' as IntlString,
    User: '' as IntlString,
    Maintainer: '' as IntlString,
    Guest: '' as IntlString,
    Owner: '' as IntlString,
    MinValue: '' as IntlString,
    MaxValue: '' as IntlString,
    IntegerOnly: '' as IntlString,
    OwnerFirstName: '' as IntlString,
    OwnerLastName: '' as IntlString,
    Role: '' as IntlString,
    FailedToSave: '' as IntlString,
    ImportEnum: '' as IntlString,
    ImportEnumCopy: '' as IntlString,
    CreateMixin: '' as IntlString,
    OldNames: '' as IntlString,
    NewClassName: '' as IntlString,
    HideAttribute: '' as IntlString,
    ShowAttribute: '' as IntlString,
    Visibility: '' as IntlString,
    Hidden: '' as IntlString,
    DefaultValue: '' as IntlString,
    SelectAValue: '' as IntlString,
    DateOnly: '' as IntlString,
    OnlyTime: '' as IntlString,
    DateAndTime: '' as IntlString,
    Configuration: '' as IntlString,
    ConfigurationEnabled: '' as IntlString,
    ConfigurationDisabled: '' as IntlString,
    ConfigDisable: '' as IntlString,
    ConfigEnable: '' as IntlString,
    ConfigBeta: '' as IntlString,
    ClassSettingHint: '' as IntlString,
    ClassProperties: '' as IntlString,
    Mixins: '' as IntlString,
    BaseClasses: '' as IntlString,
    ClassColon: '' as IntlString,
    MixinColon: '' as IntlString,
    NewSpaceType: '' as IntlString,
    SpaceTypeTitle: '' as IntlString,
    Description: '' as IntlString,
    CountSpaces: '' as IntlString,
    RoleName: '' as IntlString,
    Permissions: '' as IntlString,
    Assignees: '' as IntlString,
    DeleteRole: '' as IntlString,
    DeleteRoleConfirmation: '' as IntlString,
    DeleteWorkspace: '' as IntlString,
    DeleteWorkspaceConfirm: '' as IntlString,
    DeleteSpaceType: '' as IntlString,
    DeleteSpaceTypeConfirm: '' as IntlString,
    WorkspaceName: '' as IntlString,
    Workspace: '' as IntlString,
    Calendar: '' as IntlString,
    StartOfTheWeek: '' as IntlString,
    SystemSetupString: '' as IntlString,
    DefaultString: '' as IntlString,
    WorkspaceNamePattern: '' as IntlString,
    DisablePermissions: '' as IntlString,
    EnablePermissions: '' as IntlString,
    DisablePermissionsConfirmation: '' as IntlString,
    EnablePermissionsConfirmation: '' as IntlString,
    BetaWarning: '' as IntlString,
    DangerZone: '' as IntlString,
    AccessControl: '' as IntlString,
    GuestAccess: '' as IntlString,
    GuestAccessDescription: '' as IntlString,
    GuestSignUpDescription: '' as IntlString,
    GuestChannelsDescription: '' as IntlString,
    GuestChannelsArrayLabel: '' as IntlString,
    ApiAccess: '' as IntlString,
    CreateApiKey: '' as IntlString,
    ApiKeyName: '' as IntlString,
    ApiKeyOperations: '' as IntlString,
    ApiKeyOperationsHint: '' as IntlString,
    ApiKeyExpiresOn: '' as IntlString,
    ApiKeyTokenTtl: '' as IntlString,
    ApiKeyTokenTtlHint: '' as IntlString,
    ApiKeyTokenTtlDays: '' as IntlString,
    ApiKeyCreatedOn: '' as IntlString,
    ApiKeyLastUsed: '' as IntlString,
    ApiKeyNeverUsed: '' as IntlString,
    ApiKeyRevoked: '' as IntlString,
    ApiKeyReadOnly: '' as IntlString,
    RevokeApiKey: '' as IntlString,
    RevokeApiKeyConfirm: '' as IntlString,
    ApiKeyCreated: '' as IntlString,
    ApiKeyShownOnceHint: '' as IntlString,
    NoApiKeys: '' as IntlString,
    ApiKeysUsage: '' as IntlString,
    ApiKeyLimitReachedError: '' as IntlString,
    PersonalApiKeys: '' as IntlString,
    IntegrationApiKeys: '' as IntlString,
    CreatePersonalApiKey: '' as IntlString,
    CreateIntegrationApiKey: '' as IntlString,
    PersonalApiKeyHint: '' as IntlString,
    ApiKeyFullRights: '' as IntlString,
    ApiKeySpaces: '' as IntlString,
    ApiKeyAddAll: '' as IntlString,
    ApiKeySpacesHint: '' as IntlString,
    ApiKeySpacesPlaceholder: '' as IntlString,
    ApiKeyAllSpaces: '' as IntlString,
    ApiKeyIncomingAllowed: '' as IntlString,
    ApiKeyIncomingNotAllowed: '' as IntlString,
    ApiKeyAllowIncoming: '' as IntlString,
    ApiKeyAllowIncomingHint: '' as IntlString,
    ApiKeyColumnKey: '' as IntlString,
    ApiKeyColumnIncoming: '' as IntlString,
    ApiKeyColumnRights: '' as IntlString,
    ApiKeyOpsCount: '' as IntlString,
    ImportDocumentPermission: '' as IntlString,
    ImportDocumentDescription: '' as IntlString,
    SelectUsers: '' as IntlString,
    ManageIdentities: '' as IntlString,
    AddNew: '' as IntlString,
    Release: '' as IntlString,
    ReleaseSocialId: '' as IntlString,
    ReleaseSocialIdConfirm: '' as IntlString,
    ReleasePrimarySocialId: '' as IntlString,
    ReleasePrimarySocialIdConfirm: '' as IntlString,
    Login: '' as IntlString,
    Primary: '' as IntlString,
    IdentifierExists: '' as IntlString,
    Reset: '' as IntlString,
    Restricted: '' as IntlString,
    RestrictedAttributeWarning: '' as IntlString,
    PasswordAgingRule: '' as IntlString,
    PasswordAgingRuleDescription: '' as IntlString,
    ShowInTitle: '' as IntlString,
    SpaceMembersOnly: '' as IntlString,
    LastOwnerLeaveTitle: '' as IntlString,
    LastOwnerLeaveMessage: '' as IntlString,
    OverrideAttribute: '' as IntlString,
    Required: '' as IntlString,

    WebhookAccess: '' as IntlString,
    WebhookIncomingAccess: '' as IntlString,
    WebhookConstruct: '' as IntlString,
    WebhookConstructHint: '' as IntlString,
    WebhookConstructOperation: '' as IntlString,
    WebhookConstructTarget: '' as IntlString,
    WebhookConstructPickTarget: '' as IntlString,
    WebhookIncomingPlaceholderProject: '' as IntlString,
    WebhookIncomingPlaceholderChannel: '' as IntlString,
    WebhookIncomingPlaceholderTeamspace: '' as IntlString,
    WebhookIncomingPlaceholderIssue: '' as IntlString,
    WebhookIncomingPlaceholderDocument: '' as IntlString,
    WebhookIncomingEndpoint: '' as IntlString,
    WebhookIncomingEndpointHeaderAuth: '' as IntlString,
    WebhookIncomingEndpointPathAuth: '' as IntlString,
    AddWebhook: '' as IntlString,
    NoWebhooks: '' as IntlString,
    WebhookUrl: '' as IntlString,
    WebhookUrlPlaceholder: '' as IntlString,
    WebhookUrlHttpsOnly: '' as IntlString,
    WebhookEventsLabel: '' as IntlString,
    WebhookEventsHint: '' as IntlString,
    WebhookSpaces: '' as IntlString,
    WebhookSpacesHint: '' as IntlString,
    WebhookEventIssueCreated: '' as IntlString,
    WebhookEventIssueStatusChanged: '' as IntlString,
    WebhookEventIssueAssigned: '' as IntlString,
    WebhookEventIssueCommented: '' as IntlString,
    WebhookEventMessagePosted: '' as IntlString,
    WebhookEventDocumentCreated: '' as IntlString,
    WebhookExamplePayload: '' as IntlString,
    WebhookEnabled: '' as IntlString,
    WebhookDisabled: '' as IntlString,
    WebhookFailureCount: '' as IntlString,
    WebhookLastDelivery: '' as IntlString,
    WebhookLastError: '' as IntlString,
    WebhookNeverDelivered: '' as IntlString,
    WebhookCreate: '' as IntlString,
    WebhookSaveChanges: '' as IntlString,
    WebhookManage: '' as IntlString,
    WebhookSecrets: '' as IntlString,
    WebhookSecretShownHint: '' as IntlString,
    WebhookSecretReveal: '' as IntlString,
    WebhookSecretHide: '' as IntlString,
    WebhookSecretAdd: '' as IntlString,
    WebhookSecretAddHint: '' as IntlString,
    WebhookSecretRevoke: '' as IntlString,
    WebhookSecretRevokeConfirm: '' as IntlString,
    WebhookSecretMinOne: '' as IntlString,
    WebhookSecretMaxTwo: '' as IntlString,
    WebhookSecretCreatedOn: '' as IntlString,
    WebhookDeliveries: '' as IntlString,
    WebhookDeliveriesEmpty: '' as IntlString,
    WebhookDeliverySuccess: '' as IntlString,
    WebhookDeliveryFailed: '' as IntlString,
    WebhookSendTest: '' as IntlString,
    WebhookTestSuccess: '' as IntlString,
    WebhookTestFailure: '' as IntlString,
    WebhookDelete: '' as IntlString,
    WebhookDeleteConfirm: '' as IntlString,
    WebhookEventDeliveredCount: '' as IntlString,
    ApiKeyOperationCounts: '' as IntlString
  }
})
