# Region configuration for local development
# See docs/region_config.md for format details

regions:
  '':
    name: Default
    transactors:
      - external: ws://localhost:8087/_tr
        internal: ws://transactor:3332
    collaborators:
      - external: ws://localhost:8087/_cl
        internal: ws://collaborator0:3078
