//
// Copyright © 2026 Intabia Fusion.
//
// Licensed under the Eclipse Public License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License. You may
// obtain a copy of the License at https://www.eclipse.org/legal/epl-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//
// See the License for the specific language governing permissions and
// limitations under the License.
//

import { prepareStand, restoreStand } from './stand'
import { stands } from './stands'

const name = process.argv[2]
const mode = process.argv[3] ?? 'prepare'
const cfg = stands[name]

if (cfg === undefined || (mode !== 'prepare' && mode !== 'restore')) {
  console.error(`usage: dev/test-base/run.sh <${Object.keys(stands).join('|')}> [prepare|restore]`)
  process.exit(1)
}

// Overlays generated by the caller (profiling, pinned image versions).
const extra = (process.env.STAND_EXTRA_COMPOSE ?? '')
  .split(',')
  .map((it) => it.trim())
  .filter((it) => it.length > 0)

const target = { ...cfg, composeFiles: [...cfg.composeFiles, ...extra] }

void (mode === 'restore' ? restoreStand(target) : prepareStand(target))
  .then(() => {
    process.exit(0)
  })
  .catch((err) => {
    console.error(err)
    process.exit(1)
  })
