//
// Copyright © 2026 Intabia Fusion.
//
// Licensed under the Eclipse Public License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License. You may
// obtain a copy of the License at https://www.eclipse.org/legal/epl-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//
// See the License for the specific language governing permissions and
// limitations under the License.
//

import admin, { adminId } from '@hcengineering/admin'
import { type IntlString, mergeIds } from '@hcengineering/platform'

export default mergeIds(adminId, admin, {
  string: {
    WorkspacesAdminTitle: '' as IntlString,
    General: '' as IntlString,
    Payments: '' as IntlString,
    PaymentOperations: '' as IntlString,
    UpcomingRenewals: '' as IntlString,
    TotalCharges: '' as IntlString,
    TotalAmount: '' as IntlString,
    TotalErrors: '' as IntlString,
    Operation: '' as IntlString,
    Event: '' as IntlString,
    CurrentPlan: '' as IntlString,
    Actor: '' as IntlString,
    Amount: '' as IntlString,
    Date: '' as IntlString,
    Payer: '' as IntlString,
    RenewalDate: '' as IntlString,
    OnlyPaid: '' as IntlString,
    OnlyFree: '' as IntlString,
    OnlyTrial: '' as IntlString,
    TrialingOnly: '' as IntlString,
    SortByAmount: '' as IntlString,
    Period7d: '' as IntlString,
    Period30d: '' as IntlString,
    Period90d: '' as IntlString,
    Period365d: '' as IntlString,
    MonthlyFinance: '' as IntlString,
    CancelsAndRefunds: '' as IntlString,
    GroupByWorkspace: '' as IntlString,
    GroupByPayment: '' as IntlString,
    FailedRenewals: '' as IntlString,
    RevenueByWorkspace: '' as IntlString,
    OnlyErrors: '' as IntlString,
    Attempt: '' as IntlString,
    AllOperations: '' as IntlString,
    NoOperations: '' as IntlString,
    LiveStats: '' as IntlString,
    PaidSeats: '' as IntlString,
    Services: '' as IntlString,
    Statistics: '' as IntlString,
    ServerManager: '' as IntlString,
    Reports: '' as IntlString,
    CreateReport: '' as IntlString,
    ReportAccounts: '' as IntlString,
    ReportWorkspaces: '' as IntlString,
    ReportPaidWorkspaces: '' as IntlString,
    Service: '' as IntlString,
    Registrations: '' as IntlString,
    AccountsPerMonth: '' as IntlString,
    WorkspacesPerMonth: '' as IntlString,
    PaidSeatsPerMonth: '' as IntlString,
    TrialSeatsPerMonth: '' as IntlString,
    Days30: '' as IntlString,
    Days90: '' as IntlString,
    Refresh: '' as IntlString,
    AutoRefresh: '' as IntlString,
    UpdatedAt: '' as IntlString,
    AccountsAdminTitle: '' as IntlString,
    EnableDeletion: '' as IntlString,
    ShowActive: '' as IntlString,
    ShowArchived: '' as IntlString,
    ShowDeleted: '' as IntlString,
    ShowOther: '' as IntlString,
    ShowAttempts: '' as IntlString,
    ShowInactive: '' as IntlString,
    SortingOrder: '' as IntlString,
    MigrationRegion: '' as IntlString,
    FilterRegion: '' as IntlString,
    MoreItems: '' as IntlString,
    OpenWorkspaceUrl: '' as IntlString,
    CopyUuid: '' as IntlString,
    Details: '' as IntlString,
    Usage: '' as IntlString,
    Backup: '' as IntlString,
    Info: '' as IntlString,
    WeeklyActivity: '' as IntlString,
    NoActivity: '' as IntlString,
    Members: '' as IntlString,
    Role: '' as IntlString,
    LastActivity: '' as IntlString,
    ActivityByWorkspaces: '' as IntlString,
    Subscriptions: '' as IntlString,
    Archive: '' as IntlString,
    Unarchive: '' as IntlString,
    Migrate: '' as IntlString,
    Delete: '' as IntlString,
    Previous: '' as IntlString,
    Next: '' as IntlString,
    Page: '' as IntlString,
    SocialIds: '' as IntlString,
    NoSubscriptions: '' as IntlString,
    CreateSubscription: '' as IntlString,
    Plan: '' as IntlString,
    BillingExpired: '' as IntlString,
    Seats: '' as IntlString,
    PeriodDays: '' as IntlString,
    AsTrial: '' as IntlString,
    GroupByName: '' as IntlString,
    Create: '' as IntlString,
    ReplaceSubscription: '' as IntlString,
    Total: '' as IntlString,
    Users: '' as IntlString,
    Connections: '' as IntlString,
    ActiveWorkspaces: '' as IntlString,
    Disk: '' as IntlString,
    Projects: '' as IntlString,
    AITokens: '' as IntlString,
    MeetingMinutes: '' as IntlString,
    Data: '' as IntlString,
    Blobs: '' as IntlString,
    Backups: '' as IntlString,
    LastBackup: '' as IntlString,
    Mode: '' as IntlString,
    Region: '' as IntlString,
    CreatedOn: '' as IntlString,
    LastVisit: '' as IntlString,
    Email: '' as IntlString,
    Type: '' as IntlString,
    Status: '' as IntlString,
    Provider: '' as IntlString,
    PeriodEnd: '' as IntlString,
    TrialEnd: '' as IntlString,
    Tx: '' as IntlString,
    Name: '' as IntlString,
    Url: '' as IntlString,
    Uuid: '' as IntlString,
    Workspace: '' as IntlString,
    Timezone: '' as IntlString,
    AllPlans: '' as IntlString,
    LoadError: '' as IntlString,
    RefreshOff: '' as IntlString,
    Seconds15: '' as IntlString,
    Minute1: '' as IntlString,
    Minutes5: '' as IntlString,
    Minutes15: '' as IntlString,
    OtpConfirmTitle: '' as IntlString,
    OtpSent: '' as IntlString,
    OtpSendFailed: '' as IntlString,
    OtpCode: '' as IntlString,
    SendCode: '' as IntlString,
    Confirm: '' as IntlString,
    AddMember: '' as IntlString,
    RemoveMember: '' as IntlString,
    Add: '' as IntlString,
    Reindex: '' as IntlString,
    ReindexAll: '' as IntlString,
    CreateWorkspace: '' as IntlString,
    Edit: '' as IntlString,
    Save: '' as IntlString,
    DisabledFeaturesOverride: '' as IntlString,
    EditSubscription: '' as IntlString,
    CancelSubscription: '' as IntlString,
    SearchAccounts: '' as IntlString,
    PleaseConfirm: '' as IntlString,
    SortActiveUsers: '' as IntlString,
    SortName: '' as IntlString,
    SortBackupDate: '' as IntlString,
    SortBackupSize: '' as IntlString,
    SortLastVisit: '' as IntlString,
    MassArchive: '' as IntlString,
    MassMigrate: '' as IntlString,
    ResetAttempts: '' as IntlString,
    UnarchiveWorkspace: '' as IntlString,
    ReplaceSubscriptionConfirm: '' as IntlString
  }
})
