//
// Copyright © 2026 Intabia Fusion.
//
// Licensed under the Eclipse Public License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License. You may
// obtain a copy of the License at https://www.eclipse.org/legal/epl-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//
// See the License for the specific language governing permissions and
// limitations under the License.
//
import { faker } from '@faker-js/faker'
import { type WorkspaceUuid } from '@hcengineering/core'

import { getStorageStats, getStorageStatsByType, waitForDerivedBlobs } from '../API/Datalake'
import { expect, test, type Page } from '../fixtures'
import { DriveCreateEditPopup } from '../model/drive/drive-create-edit-popup'
import { DriveFilesPage } from '../model/drive/drive-files-page'
import { DriveLeftMenu } from '../model/drive/drive-left-menu'
import { DrivesPage } from '../model/drive/drive-drives-page'
import { generateId, loginByToken, uploadFile } from '../utils'

// Generated by tests/make-media-fixtures.sh when the stand comes up: 1280x720, 3s, h264 + aac.
const VIDEO = 'fake-video.mp4'

// A 720p source yields 6 artifacts on this stand: the master playlist, a playlist and one segment
// for each of the two renditions the ladder picks (orig + 480p), and the thumbnail. Asserting on 4
// leaves room for the ladder to change without turning this into a brittle exact-count check,
// while still proving more than a bare copy of the source happened.
const MIN_DERIVED_BLOBS = 4

/** Plays the video element and reports whether it actually advanced. */
async function playAndMeasure (page: Page): Promise<{ played: boolean, poster: string }> {
  return await page.evaluate(async () => {
    const video = document.querySelector('video')
    if (video == null) return { played: false, poster: '' }
    try {
      await video.play()
    } catch {
      return { played: false, poster: video.poster }
    }
    await new Promise((resolve) => setTimeout(resolve, 3000))
    return { played: video.currentTime > 0 && video.readyState >= 2, poster: video.poster }
  })
}

test.describe('Drive video transcoding tests', () => {
  let leftMenu: DriveLeftMenu
  let popupDrive: DriveCreateEditPopup
  let drivesPage: DrivesPage
  let filesPage: DriveFilesPage
  let driveName: string
  let workspace: WorkspaceUuid

  test.beforeEach(async ({ page, sharedWorkspace }) => {
    const shared = await sharedWorkspace()
    workspace = shared.ws.workspace

    popupDrive = new DriveCreateEditPopup(page)
    leftMenu = new DriveLeftMenu(page)
    drivesPage = new DrivesPage(page)
    filesPage = new DriveFilesPage(page)
    driveName = `${faker.word.noun()}-${generateId(5)}`

    await loginByToken(page, shared.token, shared.ws, 'drive')
    await leftMenu.clickCreateNewDrive()
    await popupDrive.createOrEditDrive({ name: driveName })
    await leftMenu.clickDrives()
    await drivesPage.clickOnDrive({ name: driveName })
  })

  test('Uploaded video is transcoded and plays back over HLS', async ({ page }) => {
    await test.step('upload the video', async () => {
      await uploadFile(page, VIDEO, 'Upload files')
      await filesPage.checkFileExists(VIDEO)
    })

    await test.step('stream transcodes it into HLS artifacts', async () => {
      const stats = await waitForDerivedBlobs(workspace, MIN_DERIVED_BLOBS)
      expect(stats.derivedCount).toBeGreaterThanOrEqual(MIN_DERIVED_BLOBS)
      expect(stats.derivedSize).toBeGreaterThan(0)
    })

    await test.step('the player advances through the stream', async () => {
      await filesPage.linkFile(VIDEO).click()
      await expect(page.locator('video')).toBeVisible()
      const { played, poster } = await playAndMeasure(page)
      expect(played, 'video must advance past the first frame').toBe(true)
      // The plain <video> fallback never gets a poster; the HLS branch sets it to the thumbnail
      // the transcoder produced, so this tells the two apart.
      expect(poster, 'HLS branch must set the generated thumbnail as poster').not.toBe('')
    })
  })

  test('Storage usage counts the transcoded output and frees it on delete', async ({ page }) => {
    const before = await getStorageStats(workspace)

    await test.step('upload and wait for transcoding', async () => {
      await uploadFile(page, VIDEO, 'Upload files')
      await filesPage.checkFileExists(VIDEO)
      await waitForDerivedBlobs(workspace, MIN_DERIVED_BLOBS)
    })

    const after = await getStorageStats(workspace)

    await test.step('usage grows by the source plus its renditions', async () => {
      expect(after.count).toBeGreaterThan(before.count)
      expect(after.size).toBeGreaterThan(before.size)
      // The whole point of the derived breakdown: the user can see how much of the growth is
      // generated rather than uploaded.
      expect(after.derivedSize).toBeGreaterThan(before.derivedSize)
      expect(after.size - after.derivedSize).toBeGreaterThan(before.size - before.derivedSize)

      const video = (await getStorageStatsByType(workspace)).find((t) => t.type === 'video')
      expect(video, 'a video bucket must appear').toBeDefined()
      expect(video?.derivedSize ?? 0).toBeGreaterThan(0)
    })

    await test.step('deleting the video releases the source and every rendition', async () => {
      await filesPage.deleteFile(VIDEO)
      await filesPage.checkFileNotExists(VIDEO)

      await expect
        .poll(async () => (await getStorageStats(workspace)).size, {
          message: 'workspace usage must return to what it was before the upload',
          timeout: 60000
        })
        .toBe(before.size)

      const freed = await getStorageStats(workspace)
      expect(freed.count).toBe(before.count)
      expect(freed.derivedCount).toBe(before.derivedCount)
    })
  })
})
