//
// Copyright © 2026 Intabia Fusion.
//
// Licensed under the Eclipse Public License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License. You may
// obtain a copy of the License at https://www.eclipse.org/legal/epl-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//
// See the License for the specific language governing permissions and
// limitations under the License.
//
import { systemAccountUuid, type WorkspaceUuid } from '@hcengineering/core'
import { generateToken } from '@hcengineering/server-token'
import { PlatformURI } from '../utils'

/** Nginx proxies the datalake pod under this prefix on the sanity stand. */
const datalakeUrl = `${PlatformURI}/_datalake`

export interface WorkspaceStorageStats {
  count: number
  size: number
  /** Subset of the above generated by transcoding (blob.parent is set), not uploaded by a user. */
  derivedCount: number
  derivedSize: number
}

export interface WorkspaceStorageStatsByType extends WorkspaceStorageStats {
  type: string
}

function serviceToken (): string {
  return generateToken(systemAccountUuid, undefined, { service: 'sanity' }, 'secret')
}

async function get<T> (path: string): Promise<T> {
  const response = await fetch(`${datalakeUrl}/${path}`, {
    headers: { Authorization: `Bearer ${serviceToken()}` }
  })
  if (!response.ok) {
    throw new Error(`datalake ${path} failed: ${response.status} ${await response.text()}`)
  }
  return (await response.json()) as T
}

export async function getStorageStats (workspace: WorkspaceUuid): Promise<WorkspaceStorageStats> {
  return await get<WorkspaceStorageStats>(`stats/${workspace}`)
}

export async function getStorageStatsByType (workspace: WorkspaceUuid): Promise<WorkspaceStorageStatsByType[]> {
  return await get<WorkspaceStorageStatsByType[]>(`stats/${workspace}/by-type`)
}

/**
 * Transcoding is asynchronous: the platform publishes to `stream.transcode.request` and the stream
 * pod uploads playlists and segments back one by one. Poll until the derived blobs settle.
 */
export async function waitForDerivedBlobs (
  workspace: WorkspaceUuid,
  minCount: number,
  timeoutMs = 120000
): Promise<WorkspaceStorageStats> {
  const deadline = Date.now() + timeoutMs
  let last = await getStorageStats(workspace)
  while (Date.now() < deadline) {
    if (last.derivedCount >= minCount) return last
    await new Promise((resolve) => setTimeout(resolve, 1000))
    last = await getStorageStats(workspace)
  }
  throw new Error(`timed out waiting for ${minCount} derived blobs, last seen: ${JSON.stringify(last)}`)
}

/** Poll until the workspace total drops to or below the expected size (deletion is a soft delete). */
export async function waitForStorageSizeAtMost (
  workspace: WorkspaceUuid,
  maxSize: number,
  timeoutMs = 60000
): Promise<WorkspaceStorageStats> {
  const deadline = Date.now() + timeoutMs
  let last = await getStorageStats(workspace)
  while (Date.now() < deadline) {
    if (last.size <= maxSize) return last
    await new Promise((resolve) => setTimeout(resolve, 500))
    last = await getStorageStats(workspace)
  }
  throw new Error(`timed out waiting for size <= ${maxSize}, last seen: ${JSON.stringify(last)}`)
}
